/**
 * reportExporter.ts
 * Data-layer helper that writes a generated HTML report to a user-chosen
 * local path via VS Code's built-in filesystem API.
 *
 * No network calls are made — this is fully offline (NF-09).
 * The exported HTML file is self-contained and prints to PDF natively
 * via the browser's Ctrl+P dialog.
 *
 * FR-10: htmlContent is generated by ReportGenerator and contains only
 * behavioral metadata — never any code content.
 */

import * as vscode from 'vscode';
import { SessionReport } from '../business/reportGenerator';

/**
 * Opens a save dialog, writes the HTML report to the chosen path, and
 * prompts the user to open the file in their default browser.
 */
export async function exportReportAsHTML(
  report: SessionReport,
  htmlContent: string
): Promise<void> {
  // 1. Open a save dialog pre-filled with a date-stamped filename
  const uri = await vscode.window.showSaveDialog({
    defaultUri: vscode.Uri.file(
      `bounded-report-${new Date().toISOString().split('T')[0]}.html`
    ),
    filters: {
      'HTML Report': ['html']
    },
    saveLabel: 'Save Report'
  });

  // 2. User cancelled — return silently
  if (!uri) { return; }

  // 3. Write the HTML string to the chosen path using VS Code's fs API
  const encoder = new TextEncoder();
  await vscode.workspace.fs.writeFile(uri, encoder.encode(htmlContent));

  // 4. Inform the user and offer to open the file
  const action = await vscode.window.showInformationMessage(
    'Bounded: Report saved. Open in browser and use Ctrl+P to export as PDF.',
    'Open Report'
  );

  // 5. Reveal the file in the default browser (local file — no network call)
  if (action === 'Open Report') {
    await vscode.env.openExternal(uri);
  }
}
